# Autogenerated by devscripts/update-version.py

__version__ = '2025.10.30.102111'

RELEASE_GIT_HEAD = '089c442ad448aaa9452610b2e09dfa17363349ad'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'jay36065/yt-dlp'

ORIGIN = 'jay36065/yt-dlp'

_pkg_version = '2025.10.30.102111'
